# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commapp', '0002_auto_20171024_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='announce_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=None),
        ),
    ]
